/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ddj' at '11/17/15 11:10 AM' with Gradle 2.6
 *
 * @author ddj, @date 11/17/15 11:10 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
